### PR TITLE
Add travis configuration file

### LINKED ISSUE #58: Set up continuous integration
Test should be run automatically, e.g., via travis. Merge of PRs should be conditioned on passing tests. Once the repository is public it is (fairly) easy to set up.

### PR DESCRIPTION
**Pull request by jakobj**
This PR sets up TravisCI as our continuous integration system. Travis will run the testsuite on all PRs and on the current master to make sure changes do not break the tests.

closes #58

### CODE REVIEW

**Comment by jakobj** [comment]
@WillemWybo for some reason when travis is running the tests it doesn't find netsim: https://travis-ci.org/github/unibe-cns/NEAT/builds/753335113 do you remember what the issue was? locally it works fine :/

**Comment by WillemWybo** [comment]
Hm no idea :/ does it not build the netsim module at all?

**Comment by jakobj** [comment]
i think it builds it correctly (https://travis-ci.org/github/unibe-cns/NEAT/builds/753335113#L804), just seems like an import issue

**Comment by jakobj** [comment]
let's close this and try with github actions instead.

**Pull request closed without merging**
