### PR TITLE
[WIP] Fix/setup compilechannels

### LINKED ISSUE #53: Investigate nrnivmodl and loaddll
To see if we can get by without copying the .mod files. Should probably implement some paradigm on how to handle duplicate .mod names.

### PR DESCRIPTION
**Pull request by jakobj**
- pre-netsim install hook needs to be in build_ext otherwise pip doesn't work
- compilechannels can not be called during installation as by definition NEAT is not installed yet; this needs to be called separately after installation
- mod files are specified directly and copied by setup to the correct destination
- works with `python setup.py install` and `pip install`

this is a suggestion of how to solve the installation issues. users will need to run `compilechannels default` manually if they want to have the default channels and mechanisms available. they can run `compilechannels <dir>` on any directory where they have custom channels implemented.

closes #53

### CODE REVIEW

**Comment by WillemWybo** [comment]
I did some looking around and it appears that there is a `neat/` directory missing from the python install path. The only directory I find is something weird like `neat-0.9-py3.7-macosx-10.15-x86_64.egg/`, with `neat/` inside.

**Comment by jakobj** [comment]
how did you install it?

**Comment by WillemWybo** [comment]
`python3 setup.py install`

**Comment by jakobj** [comment]
sorry, i can't reproduce your issue. do you maybe have some other neat package installed? `neat-0.9-py3.7-macosx-10.15-x86_64.egg/` looks wrong as we are at version 0.1, maybe there's a mixup? otherwise it might be a mac related issue. @benelot do you have a linux system available to check whether this works at least for all linux systems?

**Comment by jakobj** [comment]
closing in favor of #72

**Pull request closed without merging**
