### PR TITLE
Adapt package name, fix README to render on pypi, update installation instructions

### LINKED ISSUE #51: Update install instructions once NEAT is in pip
Now, the instructions in INSTALL.rst are very basic. Could you update them once we have neat on pip? @jakobj

### PR DESCRIPTION
**Pull request by jakobj**
as advertised in the title

closes #51

### CODE REVIEW

**Comment by WillemWybo** [comment]
Do we need to change the package name? If so, we have to adapt all the tests...

But I was under the impression some package had a slightly different name in pip (i.e. to install you do `pip install name_in_pip`, whereas to import you have `import name`)

**Comment by jakobj** [comment]
> Do we need to change the package name? If so, we have to adapt all the tests...
> 
> But I was under the impression some package had a slightly different name in pip (i.e. to install you do `pip install name_in_pip`, whereas to import you have `import name`)

yep, this is what's done here. the package is called "neadend" in pip, in python you still do `import neat`. not great, but the only solution if we don't want to change all imports

**Comment by WillemWybo** [comment]
I see, although on second thought, I wonder whether we should consider a name change to 'neatdend', there may be a subset of user who want to install this package and the 'NeuroEvolution of Augmenting Topologies' library.

**Comment by jakobj** [comment]
> I see, although on second thought, I wonder whether we should consider a name change to 'neatdend', there may be a subset of user who want to install this package and the 'NeuroEvolution of Augmenting Topologies' library.

it'd be a moderate time investment, so if you think it's really worth it, we can do it. if so, we should however do it in a separate PR as the changes will be too much noise to filter out in this PR.

using an intuitive estimate of the number of users who use both packages i arrive at `n=1 (+- 1)` users :P

**Comment by jakobj** [comment]
@benelot this PR introduces the `__version__` property to the package. it seems like one could use this in `conf.py` l104ff. could you please look into this?

**Pull request merged**
